name: Enviar mensaje diario a Telegram

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC = 9:00 en Bilbao
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install requests
        pip install feedparser
        pip install beautifulsoup4
        pip install lxml

    - name: Ejecutar el script
      run: python bot.py
